version: "3.9"

services:
  admin-ui:
    container_name: ms-delivery-admin-ui
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
